### ISSUE TITLE
Private networking

### ISSUE THREAD

**Issue by dayblox** [Andrew-Bekhiet/railway_tailscale_vpn#2]
Using your template, I appear to have managed to connect to the private railway network and to ping the exit node, but can't seem to ping the services in the network via their railway private domain.
Have you tried doing so?

**Comment by Andrew-Bekhiet** [comment]
Yeah you can ping the exit node because it has tailscale installed and is part of your tailnet, but to access other railway services you need either

1. Install tailscale on every service you need to get access to, or

2. SSH into the exit node then connect to other services through the exit node's SSH session

Railway private domains work by DNS resolution in railway network, what tailscale does is that it routes your traffic through the exit node, but DNS resolution is done by tailscale DNS so it can't resolve railway's private domain names

**Comment by dayblox** [comment]
I am not able to install tailscale on the service, nor am I able to SSH into it.
What's weird is that the hostname appears to be resolved in some way, because pinging the correct internal hostname hangs whereas pinging a non existing one just fails right away. Any ideas?

**Comment by dayblox** [comment]
Also, is there a way to use subnet to allow the exit node to act as passthrough?

**Comment by Andrew-Bekhiet** [comment]
You can see [subnet routes](https://tailscale.com/kb/1019/subnets/), but it requires knowing the service ip which railway doesn't like

**Comment by dayblox** [comment]
Is this project intended to be embedded into every railway service we intend to connect to?
If it is the case, how do we do so?

**Comment by Andrew-Bekhiet** [comment]
No this project was intended to be used as a personal VPN, but tailscale itself can be used for many things in networking

**Comment by dayblox** [comment]
Have you managed to access things via tailscale via railway?

**Comment by Andrew-Bekhiet** [comment]
No because this is not the purpose of this repo

**Comment by Andrew-Bekhiet** [comment]
There is now [tailscale subnet router](https://railway.app/new/template/tailscale) template from the official railway team, which does exactly what you need here
Let me know if you have more questions, I'd be happy to help
